const categories = {
  income: ["salary", "freelance", "investments", "donations", "other"],
  housing: [
    "rent",
    "utilities",
    "bills",
    "home-insurance",
    "repairs",
    "property-tax",
  ],
  transportation: [
    "fuel",
    "public-transit",
    "car-payments",
    "car-insurance",
    "maintenance",
    "parking-fees",
    "tolls",
  ],
  food: ["groceries", "dining-out", "takeout", "snacks"],
  health: [
    "health-insurance",
    "medications",
    "gym-membership",
    "fitness-classes",
    "supplements",
  ],
  entertainment: [
    "streaming-services",
    "theater",
    "events",
    "hobbies",
    "games",
  ],
  personalCare: [
    "haircuts",
    "beauty-products",
    "skincare-products",
    "spa-visits",
  ],
  education: ["tuition-fees", "books", "online-courses", "workshops"],
  family: [
    "childcare",
    "school-fees",
    "baby-supplies",
    "child-activities",
    "elder-care",
  ],
  debt: [
    "credit-card-payments",
    "student-loan-payments",
    "personal-loan-payments",
    "housing-loan-payments",
    "car-loan-payments",
  ],
  savings: ["retirement-savings", "emergency-fund", "investments", "other"],
  insurance: [
    "life-insurance",
    "health-insurance",
    "car-insurance",
    "home-insurance",
    "travel-nsurance",
  ],
  gifts: ["gifts", "charitable-donations", "other-donations"],
  travel: ["flights", "transportation", "food", "entertainment", "shopping"],
  miscellaneous: [
    "pet-care",
    "legal-fees",
    "subscriptions",
    "bank-fees",
    "taxes",
    "miscellaneous",
  ],
  business: [
    "business-travel",
    "supplies-and-equipment",
    "client-gifts",
    "professional-memberships",
    "work-related-subscriptions",
  ],
  taxes: ["income-tax", "sales-tax", "property-tax", "other"],
};

export default categories;
